### ISSUE TITLE
Default exclude is inconsistent with default extensions in nyc (tsx, jsx)

### ISSUE THREAD

**Issue by jupl** [istanbuljs/schema#11]
If I have test files with a `jsx` or `tsx` extension, those test files are included in the coverage reports, which is not the expected behavior. If I have test files with `js` or `ts`, coverage reports do not have those test files as expected.

**Comment by coreyfarrell** [comment]
Thanks for raising this issue, I am not a user of `jsx`, `tsx` or even `ts` so I do my best but rely on users to inform me of oversights like this.  I never considered the possibility that a test file would have a `jsx` or `tsx` extension.  I'm working on a patch which will keep default test exclusions in sync with default extensions.
